services:
  quiz-bot:
    build: .
    container_name: quiz-solver-bot
    restart: unless-stopped
    env_file:
      - path: .env
        required: false
      - path: /home/andrey/.config/docker/telegram-bot-proxy.env
        required: false
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
