services:
  quiz-bot:
    build: .
    container_name: quiz-solver-bot
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./app.log:/app/app.log
