"""add total_questions to TestAttempt, and delete unused fields in AttemptAnswer

Revision ID: b1350ac60957
Revises: 7da86547537f
Create Date: 2025-02-05 22:34:18.646407

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b1350ac60957"
down_revision: Union[str, None] = "7da86547537f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("attemptanswers", "given_answer")
    op.drop_column("attemptanswers", "given_option_id")
    op.add_column(
        "testattempts", sa.Column("total_questions", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("testattempts", "total_questions")
    op.add_column(
        "attemptanswers", sa.Column("given_option_id", sa.INTEGER(), nullable=True)
    )
    op.add_column("attemptanswers", sa.Column("given_answer", sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
